[package]
name = "ever-crypto"
version = "0.1.0"
edition = "2018"

[dependencies]
aes-ctr = '0.6.0'
async-trait = '0.1.22'
base64 = '0.13'
curve25519-dalek = '3.2'
ed25519 = '1.0'
ed25519-dalek = '1.0'
failure = '0.1.6'
rand = '0.7'
serde_json = '1.0.41'
serde = { features = [ 'derive', 'rc' ], version = '1.0.105' }
sha2 = '0.9'
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
x25519-dalek = '1.2'

ton_api = { git = 'ssh://git@github.com/tonlabs/ton-tl.git', package = 'ton_api'}
ton_types = { git = 'ssh://git@github.com/tonlabs/ton-types.git' }
